#!/bin/bash

export COMPOSER_ROOT_VERSION=$(node -p "require('./package.json').version")

if [ "$1" == "bootstrap" ]
    then
        ./scripts/bootstrap.sh
    exit
fi

if [ "$1" == "run" ]
    then
        docker compose run --rm -e COMPOSER_ROOT_VERSION=$COMPOSER_ROOT_VERSION "${@:2}"
    exit
fi

if [ "$1" == "bun" ]
    then
        ./cli run bun $@
    exit
fi

if [ "$1" == "test" ]
    then
        ./cli run cli ./vendor/bin/phpunit "${@:2}"
    exit
fi

if [ "$1" == "testf" ]
    then
        ./cli test --filter="${@:2}"
    exit
fi

if [ "$1" == "composer" ]
    then
        ./cli run cli composer "${@:2}"
    exit
fi

./cli run cli $@
